# Generated by Django 4.1 on 2022-09-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_nombre_mascotas_animal_remove_mascotas_raza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='cumpleaños',
        ),
    ]
